# Permalinks
permalink:           pretty

# Setup
title:               zeerd's blog
tagline:             闲来生雅意，无事最逍遥。对窗遥望雪，一盏茶香飘。
url:                 http://blog.zeerd.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              zeerd
  url:               http://about.zeerd.com
  email:             emneg@zeerd.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/zeerd/zeerd.github.io

# Conversion
excerpt_separator: "<!--break-->"

pages_list:
  About: 'about/'
  Tags: 'tags/'
  Pebble: 'pebble/'
  
# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
